/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.arshin.digitallibrarymanagement;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Arshin A S
 */
public class WelcomeMenu extends JFrame {

    /**
     * Creates new form WelcomeMenu
     */
    public WelcomeMenu() {
        initComponents();

        userLoginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              dispose();
              new UserLogin(WelcomeMenu.this);
            }
        });
        adminLoginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                new AdminLogin(WelcomeMenu.this);
            }
        });

        exitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(1);
            }
        });

        this.setContentPane(this.welcomeMenuPanel);
        this.setVisible(true);
        this.setSize(1000,750);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeMenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminLoginButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        userLoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 750));

        welcomeMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Main Menu");
        welcomeMenuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 200, 40));

        adminLoginButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminLoginButton.setText("Admin Login");
//        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                adminLoginButtonActionPerformed(evt);
//            }
//        });
        welcomeMenuPanel.add(adminLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 160, 40));

        exitButton.setText("Exit");
        welcomeMenuPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, 160, 40));

        userLoginButton.setText("User Login");
        welcomeMenuPanel.add(userLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(welcomeMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton userLoginButton;
    private javax.swing.JPanel welcomeMenuPanel;
    // End of variables declaration//GEN-END:variables
}
